sudo: required
services:
   - docker
   
before_install:
   - docker build -t bpallems/docker-react -f Dockerfile.dev .
   
script:
   - docker run -e CI=true bpallems/docker-react npm run test -- --coverage